//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatBot.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air at {0} is: {1}.
        /// </summary>
        internal static string AirValueDefine {
            get {
                return ResourceManager.GetString("AirValueDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllInformation.
        /// </summary>
        internal static string AllInformation {
            get {
                return ResourceManager.GetString("AllInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are: {1}.
        /// </summary>
        internal static string AreDefine2Phrase {
            get {
                return ResourceManager.GetString("AreDefine2Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1}.
        /// </summary>
        internal static string AtDefine2Phrase {
            get {
                return ResourceManager.GetString("AtDefine2Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,{0} birght at {1} is: {2}.
        /// </summary>
        internal static string BrightValueDefine {
            get {
                return ResourceManager.GetString("BrightValueDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I would like to provide some information about the enviroment status of working location for you, please let me know what info you need?.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I cannot find any location in your input. Type &apos;help&apos; if you need assistance..
        /// </summary>
        internal static string HelpNotFoundLocation {
            get {
                return ResourceManager.GetString("HelpNotFoundLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I cannot find your input: &apos;{0}&apos;. Type &apos;help&apos; if you need assistance..
        /// </summary>
        internal static string HelpNotFoundLocationInput {
            get {
                return ResourceManager.GetString("HelpNotFoundLocationInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I did not understand &apos;{0}&apos;. Type &apos;help&apos; if you need assistance..
        /// </summary>
        internal static string HelpNotUnderstand {
            get {
                return ResourceManager.GetString("HelpNotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,{0} humidity at {1} is: {2}.
        /// </summary>
        internal static string HumidityValueDefine {
            get {
                return ResourceManager.GetString("HumidityValueDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        internal static string InDefine2Phrase {
            get {
                return ResourceManager.GetString("InDefine2Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for current status of &apos;{0}&apos;....
        /// </summary>
        internal static string LookForCurrentDefine {
            get {
                return ResourceManager.GetString("LookForCurrentDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for &apos;{0}&apos;....
        /// </summary>
        internal static string LookForDefine {
            get {
                return ResourceManager.GetString("LookForDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for &apos;{0}&apos; of &apos;{1}&apos;....
        /// </summary>
        internal static string LookForInforOfDefine {
            get {
                return ResourceManager.GetString("LookForInforOfDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        internal static string Noise {
            get {
                return ResourceManager.GetString("Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,{0} noise at {1} is: {2}.
        /// </summary>
        internal static string NoiseValueDefine {
            get {
                return ResourceManager.GetString("NoiseValueDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string OfDefine2Phrase {
            get {
                return ResourceManager.GetString("OfDefine2Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US English resource string.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        internal static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,{0} temperature at {1} is: {2}.
        /// </summary>
        internal static string TemperatureValueDefine {
            get {
                return ResourceManager.GetString("TemperatureValueDefine", resourceCulture);
            }
        }
    }
}
